/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package practica8algoritmos;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.UIManager;

/**
 *
 * @author Ferhammaren
 */
public class Ordenacioness extends javax.swing.JFrame {

    ArrayList<Persona> a = new ArrayList();
    ControlPerson o = new ControlPerson(a/*,a.size()*/);

    /**
     * Creates new form Ordenacioness
     */
    public Ordenacioness() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {"Colonia(200)", null, null, null, null},
                {"Ciudad(500)", null, null, null, null},
                {"Municipio(1100)", null, null, null, null},
                {"Estado(2500)", null, null, null, null},
                {"Pais(8000)", null, null, null, null}
            },
            new String [] {
                "", "QuickSort", "ShellSort", "Insercion", "Seleccion"
            }
        ));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jCheckBox1.setSelected(true);

        jCheckBox2.setSelected(true);

        jCheckBox3.setSelected(true);

        jCheckBox4.setSelected(true);

        jCheckBox5.setSelected(true);
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setSelected(true);

        jCheckBox7.setSelected(true);

        jCheckBox8.setSelected(true);

        jCheckBox9.setSelected(true);

        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox8)
                                    .addComponent(jCheckBox9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(69, 69, 69)
                                .addComponent(jCheckBox2)
                                .addGap(69, 69, 69)
                                .addComponent(jCheckBox3)
                                .addGap(67, 67, 67)
                                .addComponent(jCheckBox4)
                                .addGap(42, 42, 42)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7)
                        .addGap(3, 3, 3)
                        .addComponent(jCheckBox8)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox9))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       Random n=new Random();
        for (int i = 0; i <8000; i++) {
            a.add(new Persona(n.nextInt(122)));
        }
        
        if (jCheckBox1.isSelected()) {
            if (jCheckBox5.isSelected()) {
                jTable1.setValueAt(o.qsC(a),1,1);
            }
            if (jCheckBox6.isSelected()) {
                jTable1.setValueAt(o.qsCd(a), 2, 1);
            }
            if (jCheckBox7.isSelected()) {
            jTable1.setValueAt(o.qsM(a), 3, 1);
            }
             if (jCheckBox8.isSelected()) {
            jTable1.setValueAt(o.qsE(a), 4, 1);
            }
            if (jCheckBox9.isSelected()) {
            jTable1.setValueAt(o.qsP(a), 5, 1);
            }            
        }if(jCheckBox2.isSelected()){
            if (jCheckBox5.isSelected()) {
                jTable1.setValueAt(o.shellC(a),1,2);
            }
            if (jCheckBox6.isSelected()) {
                jTable1.setValueAt(o.shellCd(a), 2, 2);
            }
            if (jCheckBox7.isSelected()) {
            jTable1.setValueAt(o.shellM(a), 3, 2);
            }
             if (jCheckBox8.isSelected()) {
            jTable1.setValueAt(o.shellE(a), 4, 2);
            }
            if (jCheckBox9.isSelected()) {
            jTable1.setValueAt(o.shellP(a), 5, 2);
            } 
                                    
        }if(jCheckBox3.isSelected()){
             if (jCheckBox5.isSelected()) {
                jTable1.setValueAt(o.inserC(a),1,3);
            }
            if (jCheckBox6.isSelected()) {
                jTable1.setValueAt(o.inserCd(a), 2, 3);
            }
            if (jCheckBox7.isSelected()) {
            jTable1.setValueAt(o.inserM(a), 3, 3);
            }
             if (jCheckBox8.isSelected()) {
            jTable1.setValueAt(o.inserE(a), 4, 3);
            }
            if (jCheckBox9.isSelected()) {
            jTable1.setValueAt(o.inserP(a), 5, 3);
            } 
        }
        if (jCheckBox4.isSelected()) {
             if (jCheckBox5.isSelected()) {
                jTable1.setValueAt(o.seleC(a),1,4);
            }
            if (jCheckBox6.isSelected()) {
                jTable1.setValueAt(o.selecCd(a), 2, 4);
            }
            if (jCheckBox7.isSelected()) {
            jTable1.setValueAt(o.selecM(a), 3, 4);
            }
             if (jCheckBox8.isSelected()) {
            jTable1.setValueAt(o.selecE(a), 4, 4);
            }
            if (jCheckBox9.isSelected()) {
            jTable1.setValueAt(o.selecP(a), 5, 4);
            } 
        }
        
      

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordenacioness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordenacioness().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
